<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="img/promo-1.jpg" alt="promo">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="img/vendas.jpg" alt="venda">
      <div class="carousel-caption">
        
      </div>
    </div>
  </div>

</div>


 <div class="container" id="promocoes">
  <div class="content">
        <div id="promo__item" class="promo__item">
        <div class="promo__itens"><img src="img/promo-a.jpg" class="img-responsive" alt="Responsive image"></div>
        <div class="promo__itens"><img src="img/promo-b.jpg" class="img-responsive" alt="Responsive image"></div>
        <div class="promo__itens"><img src="img/promo-d.jpg" class="img-responsive" alt="Responsive image"></div>
        <div class="promo__itens"><img src="img/promo-e.png" class="img-responsive" alt="Responsive image"></div>           
          </div>
        </div>
    </div>
  </div>
  <!-- DESTAQUES -->
  <div class="container" id="destaques">
    <div class="content">
      <div class="heading">
      <h2>
      <span></span>
        DESTAQUES
        </h2>
       </div>
      </div>
    <div id="destaques__item" class="container__destaques">
    <article class="destaques__itens">
      <figure class="snip1321"><img src="img/produtos/Camisa1.png" alt="sq-sample26"/>
      <figcaption>
        <h4>GOSTOU?</h4>
        <a id="prod1" href="#" data-toggle="modal" data-target="#Modalprodutos1"><h2>COMPRAR</h2></a>
      </figcaption>
      </figure>
      <div class="destaques__produto">  
      <h4>Camisa1</h4>
      <p>R$99,00</p>
     </div>
    </article>
    <!-- End produto -->
     <article class="destaques__itens">
      <figure class="snip1321"><img src="img/produtos/Camisa2.png" alt="sq-sample26"/>
      <figcaption>
        <h4>GOSTOU?</h4>
        <a href="#" data-toggle="modal" data-target="#Modalprodutos2"><h2>COMPRAR</h2></a>
      </figcaption>
      </figure>
      <div class="destaques__produto">  
      <h4>Camisa1</h4>
      <p>R$99,00</p>
     </div>
    </article>
    <!-- End produto -->
     <article class="destaques__itens">
      <figure class="snip1321"><img src="img/produtos/Camisa3.png" alt="sq-sample26"/>
      <figcaption>
        <h4>GOSTOU?</h4>
       <a href="#" data-toggle="modal" data-target="#Modalprodutos3"><h2>COMPRAR</h2></a>
      </figcaption>
      </figure>
      <div class="destaques__produto">  
      <h4>Camisa1</h4>
      <p>R$99,00</p>
     </div>
    </article>
    <!-- End produto -->
     <article class="destaques__itens">
      <figure class="snip1321"><img src="img/produtos/Camisa4.png" alt="sq-sample26"/>
      <figcaption>
        <h4>GOSTOU?</h4>
        <a href="#" data-toggle="modal" data-target="#Modalprodutos4" ><h2>COMPRAR</h2></a>
      </figcaption>
      </figure>
      <div class="destaques__produto">  
      <h4>Camisa1</h4>
      <p>R$99,00</p>
     </div>
    </article>
    <!-- End produto -->
     <article class="destaques__itens">
      <figure class="snip1321"><img src="img/produtos/Camisa5.png" alt="sq-sample26"/>
      <figcaption>
        <h4>GOSTOU?</h4>
        <a href="#" data-toggle="modal" data-target="#Modalprodutos5"><h2>COMPRAR</h2></a>
      </figcaption>
      </figure>
      <div class="destaques__produto">  
      <h4>Camisa1</h4>
      <p>R$99,00</p>
     </div>
    </article>
    <!-- End produto -->
     <article class="destaques__itens">
      <figure class="snip1321"><img src="img/produtos/Camisa6.png" alt="sq-sample26"/>
      <figcaption>
        <h4>GOSTOU?</h4>
        <a href="#" data-toggle="modal" data-target="#Modalprodutos6"><h2>COMPRAR</h2></a>
      </figcaption>
      </figure>
      <div class="destaques__produto">  
      <h4>Camisa1</h4>
      <p>R$99,00</p>
     </div>
    </article>
    <!-- End produto -->
   
</div>
<!-- Modal -->
  <div class="modal fade" id="Modalprodutos1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-body">
          <div class="container-fluid">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <div class="row">
                <div class="col-md-6  ">
                <div class="img__modal"><img src="img/produtos/Camisa1.png" class="img-responsive nav-l" alt="Responsive image"></div>
                </div>
                <div class="info__modal">
                  <div class="col-md-6"><h2 class="modal-title">CAMISA</h2></div>
                  <div class="col-md-6"><h3 class="modal-title">R$ 00,00</h3></div>
                  <form action="">
                  <div class="Medidas__modal">
                  <div class="header__med">Medidas:</div>
                   <div class='range-picker' id='range-picker'>
                      <div>P</div><div>M</div><div>G</div><div class='active'>GG</div>
                    </div>
                    <div class="Frete__modal">Frete Grátis nas compras acima de R$99,00</div>
                    <button class="car__button">
                    <h4><span><i class="fa fa-shopping-cart" id="cart__modal"></i></span>Adicionar no Carrinho</h4>    
                    </button>
                    </form>
                    </div>
                    
                    </div>
                  
                  </div>
                  

                  </div> 
                  </div>
                     
                  </div>
                </div>
      
              </div>
          </div>
      </div>
      <!--- FIM DO MODAL -->
      <!-- Modal -->
  <div class="modal fade" id="Modalprodutos2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-body">
          <div class="container-fluid">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <div class="row">
                <div class="col-md-6  ">
                <div class="img__modal"><img src="img/produtos/Camisa2.png" class="img-responsive nav-l" alt="Responsive image"></div>
                </div>
                <div class="info__modal">
                  <div class="col-md-6"><h2 class="modal-title">CAMISA</h2></div>
                  <div class="col-md-6"><h3 class="modal-title">R$ 00,00</h3></div>
                  <form action="/">
                  <div class="Medidas__modal">
                  <div class="header__med">Medidas:</div>
                   <div class='range-picker' id='range-picker'>
                      <div>P</div><div>M</div><div>G</div><div class='active'>GG</div>
                    </div>
                    <div class="Frete__modal">Frete Grátis nas compras acima de R$99,00</div>
                    <button class="car__button">
                    <h4><span><i class="fa fa-shopping-cart" id="cart__modal"></i></span>Adicionar no Carrinho</h4>    
                    </button>
                    </form>
                    </div>
                    
                    </div>
                  
                  </div>
                  

                  </div> 
                  </div>
                     
                  </div>
                </div>
      
              </div>
          </div>
      </div>
      <!--- FIM DO MODAL -->
      <!-- Modal -->
  <div class="modal fade" id="Modalprodutos3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-body">
          <div class="container-fluid">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <div class="row">
                <div class="col-md-6  ">
                <div class="img__modal"><img src="img/produtos/Camisa3.png" class="img-responsive nav-l" alt="Responsive image"></div>
                </div>
                <div class="info__modal">
                  <div class="col-md-6"><h2 class="modal-title">CAMISA</h2></div>
                  <div class="col-md-6"><h3 class="modal-title">R$ 00,00</h3></div>
                  <form action="/">
                  <div class="Medidas__modal">
                  <div class="header__med">Medidas:</div>
                   <div class='range-picker' id='range-picker'>
                      <div>P</div><div>M</div><div>G</div><div class='active'>GG</div>
                    </div>
                    <div class="Frete__modal">Frete Grátis nas compras acima de R$99,00</div>
                    <button class="car__button">
                    <h4><span><i class="fa fa-shopping-cart" id="cart__modal"></i></span>Adicionar no Carrinho</h4>    
                    </button>
                    </form>
                    </div>
                    
                    </div>
                  
                  </div>
                  

                  </div> 
                  </div>
                     
                  </div>
                </div>
      
              </div>
          </div>
      </div>
      <!--- FIM DO MODAL -->
      <!-- Modal -->
  <div class="modal fade" id="Modalprodutos4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-body">
          <div class="container-fluid">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <div class="row">
                <div class="col-md-6  ">
                <div class="img__modal"><img src="img/produtos/Camisa4.png" class="img-responsive nav-l" alt="Responsive image"></div>
                </div>
                <div class="info__modal">
                  <div class="col-md-6"><h2 class="modal-title">CAMISA</h2></div>
                  <div class="col-md-6"><h3 class="modal-title">R$ 00,00</h3></div>
                  <form action="/">
                  <div class="Medidas__modal">
                  <div class="header__med">Medidas:</div>
                   <div class='range-picker' id='range-picker'>
                      <div>P</div><div>M</div><div>G</div><div class='active'>GG</div>
                    </div>
                    <div class="Frete__modal">Frete Grátis nas compras acima de R$99,00</div>
                    <button class="car__button">
                    <h4><span><i class="fa fa-shopping-cart" id="cart__modal"></i></span>Adicionar no Carrinho</h4>    
                    </button>
                    </form>
                    </div>
                    
                    </div>
                  
                  </div>
                  

                  </div> 
                  </div>
                     
                  </div>
                </div>
      
              </div>
          </div>
      </div>
      <!--- FIM DO MODAL -->
      <!-- Modal -->
  <div class="modal fade" id="Modalprodutos5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-body">
          <div class="container-fluid">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <div class="row">
                <div class="col-md-6  ">
                <div class="img__modal"><img src="img/produtos/Camisa5.png" class="img-responsive nav-l" alt="Responsive image"></div>
                </div>
                <div class="info__modal">
                  <div class="col-md-6"><h2 class="modal-title">CAMISA</h2></div>
                  <div class="col-md-6"><h3 class="modal-title">R$ 00,00</h3></div>
                  <form action="/">
                  <div class="Medidas__modal">
                  <div class="header__med">Medidas:</div>
                   <div class='range-picker' id='range-picker'>
                      <div>P</div><div>M</div><div>G</div><div class='active'>GG</div>
                    </div>
                    <div class="Frete__modal">Frete Grátis nas compras acima de R$99,00</div>
                    <button class="car__button">
                    <h4><span><i class="fa fa-shopping-cart" id="cart__modal"></i></span>Adicionar no Carrinho</h4>    
                    </button>
                    </form>
                    </div>
                    
                    </div>
                  
                  </div>
                  

                  </div> 
                  </div>
                     
                  </div>
                </div>
      
              </div>
          </div>
      </div>
      <!--- FIM DO MODAL -->
      <!-- Modal -->
  <div class="modal fade" id="Modalprodutos6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-body">
          <div class="container-fluid">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <div class="row">
                <div class="col-md-6  ">
                <div class="img__modal"><img src="img/produtos/Camisa6.png" class="img-responsive nav-l" alt="Responsive image"></div>
                </div>
                <div class="info__modal">
                  <div class="col-md-6"><h2 class="modal-title">CAMISA</h2></div>
                  <div class="col-md-6"><h3 class="modal-title">R$ 00,00</h3></div>
                  <form action="/">
                  <div class="Medidas__modal">
                  <div class="header__med">Medidas:</div>
                   <div class='range-picker' id='range-picker'>
                      <div>P</div><div>M</div><div>G</div><div class='active'>GG</div>
                    </div>
                    <div class="Frete__modal">Frete Grátis nas compras acima de R$99,00</div>
                    <button class="car__button">
                    <h4><span><i class="fa fa-shopping-cart" id="cart__modal"></i></span>Adicionar no Carrinho</h4>    
                    </button>
                    </form>
                    </div>
                    
                    </div>
                  
                  </div>
                  

                  </div> 
                  </div>
                     
                  </div>
                </div>
      
              </div>
          </div>
      </div>
      <!--- FIM DO MODAL -->
    </div>


